name: Deploy Python 3.10 Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python/

      - name: Package Layer
        run: zip -r9 layer.zip python

      - name: Deploy Layer to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws lambda publish-layer-version \
            --layer-name market-research-lambda-deps-layer \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python3.10

      - name: Update Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: |
          LAYER_VERSION=$(aws lambda list-layer-versions --layer-name market-research-lambda-deps-layer --query 'LayerVersions[0].LayerVersionArn' --output text)
          aws lambda update-function-configuration \
            --function-name market-research-lambda \
            --layers $LAYER_VERSION
          aws lambda update-function-code \
            --function-name market-research-lambda \
            --zip-file fileb://function.zip

